version: 2.1

orbs:
  android: circleci/android@2.3.0

jobs:
  build:
    docker:
      - image: cimg/android:2023.08
    steps:
      - checkout
      - restore_cache:
          key: android-orb-v1-
      - run:
          name: Chmod permissions
          command: chmod +x ./gradlew
      - run:
          name: Download Depedencies
          command: ./gradlew androidDependencies
      - save_cache:
          key: 'android-orb-v1-{{ epoch }}'
          paths:
            - ~/.android/build-cache
            - ~/.android/cache
      - run:
          name: Run Build
          command: ./gradlew build
      - store_artifacts:
          path: app/build/outputs/apk/debug/
          destination: artifact-file

  ui_test:
    executor:
      name: android/android-machine
      resource-class: large
      tag: 2023.07.1
    steps:
      - checkout
      - restore_cache:
          key: android-orb-v1-
      - android/change-java-version:
          java-version: 17
      - android/create-avd:
          avd-name: myAvd
          install: true
          system-image: system-images;android-24;default;x86
      - android/start-emulator:
          avd-name: myAvd
          no-window: true
          restore-gradle-cache-prefix: v1a
      - android/run-tests
      - android/save-gradle-cache:
          cache-prefix: v1a

  unit_test:
    docker:
      - image: cimg/android:2023.08
    steps:
      - checkout
      - restore_cache:
          key: android-orb-v1-
      - run:
          name: Run Unit Test
          command: ./gradlew clean test

workflows:
  build_and_test:
    jobs:
      - build
      - ui_test:
          requires:
            - build
      - unit_test:
          requires:
            - build